# Generated by Django 4.2.5 on 2023-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userblocked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblocked',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userblocked',
            constraint=models.UniqueConstraint(fields=('user', 'blocked_user'), name='unique_block'),
        ),
        migrations.AddConstraint(
            model_name='userfollows',
            constraint=models.UniqueConstraint(fields=('user', 'followed_user'), name='unique_follow'),
        ),
    ]
