# Generated by Django 4.2.5 on 2023-10-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu_management', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
